DELETE {
  GRAPH  <http://mu.semte.ch/application> {
    ?s ?p ?o .
  }
} INSERT {
  GRAPH  <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
  }
} WHERE {
  GRAPH  <http://mu.semte.ch/application> {
    ?s a ?type ; ?p ?o .
    VALUES ?type {
        <http://schema.org/artist>
        <http://schema.org/VisualArtwork>
        <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#FileDataObject>
        <http://xmlns.com/foaf/0.1/Person>
        <http://xmlns.com/foaf/0.1/OnlineAccount>
    }
  }
}