version: "3.4"

services:
    identifier:
        image: semtech/mu-identifier:1.10.1
        environment:
            SESSION_COOKIE_SECURE: "on"
        links:
            - dispatcher:dispatcher
    dispatcher:
        image: semtech/mu-dispatcher:2.1.0-beta.2
        links:
            - resource:resource
        volumes:
            - ./config/dispatcher:/config
    triplestore:
        image: redpencil/virtuoso:1.2.0-rc.1
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "http://mu.semte.ch/application"
        volumes:
            - ./data/db:/data
            - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
    resource:
        image: semtech/mu-cl-resources:1.22.2
        links:
            - triplestore:database
        volumes:
            - ./config/resources:/config
    file:
        image: semtech/mu-file-service:3.3.2
        links:
            - triplestore:database
        volumes:
            - ./data/files:/share
    registration:
        image: semtech/mu-registration-service:2.7.3
        links:
            - triplestore:database
    login:
        image: semtech/mu-login-service:2.8.0
        links:
            - triplestore:database
    recommendation:
        image: semtech/mu-javascript-template:1.3.5
        links:
            - triplestore:database
        environment:
            NODE_ENV: "development"
        volumes:
            - ./recommendation:/app/
    migrations:
        image: semtech/mu-migrations-service:0.9.0
        links:
            - triplestore:database
        volumes:
            - ./config/migrations:/data/migrations
